import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const lufga = localFont({
  src: "../public/fonts/Lufga-Regular.woff2",
  variable: "--font-lufga",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${lufga.variable} font-inter antialiased`}>
        {children}
      </body>
    </html>
  );
}
